# Generated by Django 3.1.7 on 2023-07-26 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
